---
version: '3.8'

services:
  node:
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
    ports:
      - 2000:2000
    command: 'npm run dev'

  storybook:
    container_name: storybook
    build:
      context: .
    ports:
      - 6006:6006
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - BROWSER=true
    command: 'npm run storybook'
